TRAIN_PATH = "/home/myeghiaz/Storage/SatClass-Real-0.125m-50px/train"
TEST_PATH = "/home/myeghiaz/Storage/SatClass-Real-0.125m-50px/test"
BATCH_SIZE = 64
# MODEL_WEIGHTS = "saved_models/baseline_model/model_final.pth"
MODEL_WEIGHTS = None
NUM_CLASSES = 1 # number of foreground classes
LR = 0.00001
N_EPOCHS = 2
TEST_SIZE = 0.2
VAL_FREQ = 1
OUTPUT_DIR = "output/"
EVAL_ONLY = False